.TH WXBANKER 1 "14 December 2008" "0.4"
.SH NAME
wxBanker \- lightweight personal finance manager
.SH DESCRIPTION
wxBanker 0.4.0.2
.PP
\fBGNOME-Do\fP allows you to quickly search for many objects present 
in your GNOME desktop environment \- applications, Evolution contacts,
Firefox bookmarks, documents \- and perform commonly used commands on 
those objects \- run, open, send, etc.

By default, wxBanker auto-saves your information after each change,
so there is no need to explicitly save anything.

This information is stored in a sqlite database located at
$HOME/.wxbanker/bank.db. For schema information please see
persistentstore.py.

.SH USAGE
wxbanker

.SH VERSION
0.4.0.2

.SH BUGS
See http://launchpad.net/wxbanker/+bugs for a list of bugs.

.SH AUTHOR
Authors of the program: see Launchpad - http://launchpad.net/wxbanker
