.TH WXBANKER 1 "7 February 2009"
.SH NAME
wxBanker \- lightweight personal finance manager
.SH DESCRIPTION
wxBanker
.PP
\fwxBanker\fP allows you easily manage your finances by keeping track
of transaction in accounts. You can add, edit, and remove accounts and
transactions from a single view as well as see the balances of all
your accounts and a grand total. Click over to the Summary view for
a graph of your total balance over time.

By default, wxBanker auto-saves your information after each change,
so there is no need to explicitly save anything. This information is
stored in a sqlite database located at $HOME/.wxbanker/bank.db.
For schema information please see model_sqlite.py.

.SH USAGE
wxbanker

.SH BUGS
See http://launchpad.net/wxbanker/+bugs for a list of bugs.

.SH AUTHOR
Authors of the program: see Launchpad - http://launchpad.net/wxbanker
